stages:
  - deploy

cache:
  paths:
    - node_modules/

deploy:
  stage: deploy
  image: rastasheep/ubuntu-sshd
  script:
    - ssh deploy@$DEPLOY_SERVER "source ~/.nvm/nvm.sh; cd blog-pi-2; git pull; npm i; hexo generate"
  before_script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
